### ISSUE TITLE
HRA

### ISSUE THREAD

**Issue by jspatterson** [TriadCare/TC_Portal#8]
1. Need two buttons at the end of the HRA:
   * Save (Save to DB without validation) Put next to Log Out in a scrolling header.
   * Complete (validate and lock-in.) Put at bottom
2. Disable 'Enter' key
3. On the question "When was the last time you had the following screenings?" Change the STD question to "Flu Vaccine".
4. Need an 'N/A' on the 'How would you describe your readiness to change in the following areas?' question grid.
5. Need to add the Current Lifestyle question.
6. Need a select all function on the grid columns. Need a tooltip to explain "Select All".

**Comment by Jackamus29** [comment]
1, 2, and 6 are features.
3, 4, and 5 are fixes that will come with the HRA update. 
The existing HRA (the one with problems) will be archived in the TCDB, but the new one will be used for all new questionnaire takers. 
The old one will be kept around to score the old HRAs.

**Comment by jspatterson** [comment]
Sounds good.  I also noticed on the Chronic Condition section, the last question Other (please specify) is a yes/no and not a text field.  I will be excited to get together or have a call soon to review priorities.  This is really looking good.

**Comment by Jackamus29** [comment]
7. Need a Spanish version.

**Comment by jspatterson** [comment]
Not sure if this is a question but the Spanish version is in the Jack 
folder.
Jeremy Patterson, PharmD

Triad Care, Inc.
302 Pomona Drive, Suite L
Greensboro, NC 27407

Office:  (336) 541-6475 ext. 101
Mobile: (336) 324-0942
Fax:     (336) 541-6485

CONFIDENTIALITY NOTICE: This e-mail message and all attachments may 
contain legally privileged and confidential information intended solely 
for the use of the addressee. If the reader of this message is not the 
intended recipient, any reading, dissemination, distribution, copying, 
or other use of this message or its attachments is prohibited. If you 
have received this communication in error, please notify the sender 
immediately by telephone at 866-885-7931 and delete this message and all 
copies and backups thereof. Thank you.




------ Original Message ------

**Comment by Jackamus29** [comment]
Not a question. 

I'm just keeping track of all my issues. 

Sorry about the confusion. 



—

**Comment by Jackamus29** [comment]
a897659d613c3619beeda7ac2923f0d105a67c6b
